name: Update Wiki

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"      - name: Clone Wiki
          git clone https://github.com/${{ github.repository }}.wiki.git

      - name: Set Repository Name
        id: repo-name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_OUTPUT

      - name: Copy Documentation Files
        run: |
          cp -r docs/* ${{ steps.repo-name.outputs.REPO_NAME }}.wiki/

      - name: Push to Wiki
        working-directory: ${{ steps.repo-name.outputs.REPO_NAME }}.wiki
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update wiki from docs"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
